spring:
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  datasource:
    url: jdbc:h2:file:./data/validation;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    password: password
    username: sa
    driver-class-name: org.h2.Driver